### PR TITLE
[Team B] 207 fix fourth button and everything else

### LINKED ISSUE #207: Fix fourth button and everything else
Connect ChatGPT LLM to Industry APIs
Various fixes

### PR DESCRIPTION
**Pull request by Stauntop-code**

### CODE REVIEW

File: team_b/yappy/lib/industry_menu.dart [hunk 1]
```diff
@@ -511,32 +513,69 @@ class _IndustryMenuState extends State<IndustryMenu> {
...
+                                  // I/flutter (17322): 
+                                  // I/flutter (17322): Seat 4: Double burger with large fries and a soda.)]
+                                  var restaurantAPI = RestaurantAPI();
+                                  validatedMenuItems = await restaurantAPI.validateMenuItems(parsedResponseList);
+                                  if (!context.mounted) return;
+                                  showModalBottomSheet(
+                                    context: context,
+                                    builder: (BuildContext context) {
+                                      // Parse the AI response to extract the text content
+                                      //String parsedResponse = aiResponse.replaceAll(RegExp(r'\[OpenAIChatCompletionChoiceMessageContentItemModel\(type: text, text: '), '').replaceAll(RegExp(r'\)\]'), '');
```
Comment (Z4sythe) [inline team_b/yappy/lib/industry_menu.dart]: Please remove these comments if unused

File: team_b/yappy/lib/industry_menu.dart [hunk 2]
```diff
@@ -511,32 +513,69 @@ class _IndustryMenuState extends State<IndustryMenu> {
...
+                                // Fetch the AI response from the database
+                                List<String> validatedMenuItems = [];
+                                
+                                try {
+                                  //if (transcript != null) {
+                                  final aiResponse = transcript['transcript_ai_response'];
+                                  String parsedResponse = aiResponse.replaceAll(RegExp(r'\[OpenAIChatCompletionChoiceMessageContentItemModel\(type: text, text: '), '').replaceAll(RegExp(r'\)\]'), '');
+                                  List<String> parsedResponseList = parsedResponse.split('\n').where((item) => item.trim().isNotEmpty).toList();
+                                  //print(parsedResponseList);
+                                  // [OpenAIChatCompletionChoiceMessageContentItemModel(type: text, text: Seat 1: Burger, fries, and a soda.
```
Comment (Z4sythe) [inline team_b/yappy/lib/industry_menu.dart:526]: Please remove these comments if unused

File: team_b/yappy/lib/services/restaurant_api_module.dart [hunk 3]
```diff
@@ -25,11 +25,14 @@ class RestaurantAPI {
...
     // 2) Check which extracted items exist in the menu
     List<String> validItems = [];
-    for (var item in extractedItems) {
-      if (menuNames.contains(item.toLowerCase())) {
-        validItems.add(item);
-      }
-    }
+        for (var item in extractedItems) {
+        for (var menuItem in menuNames) {
+          if (item.toLowerCase().contains(menuItem)) {
```
Comment (Z4sythe) [inline team_b/yappy/lib/services/restaurant_api_module.dart:30]: Nice!

File: team_b/yappy/lib/industry_menu.dart [hunk 4]
```diff
@@ -511,32 +513,69 @@ class _IndustryMenuState extends State<IndustryMenu> {
...
-                                  return KanbanBoard(tasks: [
-                                    // get the order_transcript from the restaurant table if industy is restaurant
-                                  ]);
-                                },
-                              );
+                                // Fetch the AI response from the database
+                                List<String> validatedMenuItems = [];
+                                
+                                try {
+                                  //if (transcript != null) {
```
Comment (Z4sythe) [inline team_b/yappy/lib/industry_menu.dart]: Please remove "if" null-check if not being used

**Comment by Z4sythe** [comment]
Leaving example AI Response for restaurant orders here for reference:

[OpenAIChatCompletionChoiceMessageContentItemModel(type: text, text: Seat 1: Burger, fries, and a soda.
                                  // I/flutter (17322): 
                                  // I/flutter (17322): Seat 2: Burger, fries, and a soda.
                                  // I/flutter (17322): 
                                  // I/flutter (17322): Seat 3: Burger, fries, and a soda.
                                  // I/flutter (17322): 
                                  // I/flutter (17322): Seat 4: Double burger with large fries and a soda.)]

**Review by FlyingWaffleDev — APPROVED** [review]
Extraneous comments, but everything works.

**Review by FlyingWaffleDev — APPROVED** [review]

**Review by Z4sythe — APPROVED** [review]
